/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package superadmin;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import selects.QueryClassDetails;

/**
 *
 * @author franq
 */
public class EditMeals extends javax.swing.JFrame {

    /**
     * Creates new form NewMeals
     */
    
    private int selected;
    private int totalnumclasses;
    private static String termname;
    private static String year;
    private static int termid , clsid;
    private static String fordetails,classreq;
    private static String loadedfee;
    
    public EditMeals() {
        initComponents();
        lblfee.setVisible(false);
        txtfee.setVisible(false);
        selected = 1;
        year = selects.QueryMainDetails.getCurrentYear();
        
        
        
         //get names of all members of staff
         QueryClassDetails.getClassNames();
         cmbclassname1.setModel(new DefaultComboBoxModel(QueryClassDetails.listofnames.toArray(new String[QueryClassDetails.listofnames.size()])));
         totalnumclasses = QueryClassDetails.listofnames.size();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbbordingdetails = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cmbclassname1 = new javax.swing.JComboBox();
        lblfee = new javax.swing.JLabel();
        txtfee = new javax.swing.JFormattedTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblconfirm = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jrterm1 = new javax.swing.JRadioButton();
        jrterm2 = new javax.swing.JRadioButton();
        jrterm3 = new javax.swing.JRadioButton();
        btnok = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Meals Fee");
        setIconImage(selects.QueryMainDetails.setIcon());
        setResizable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 240));
        jLabel6.setText("Enter The Meals Fee Details");

        jLabel8.setForeground(new java.awt.Color(0, 0, 240));
        jLabel8.setText("Select Boarding  Details");

        cmbbordingdetails.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Bording Meals Fee", "Day School Meals Fee" }));

        jLabel9.setForeground(new java.awt.Color(0, 0, 240));
        jLabel9.setText("Class");

        cmbclassname1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbclassname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbclassname1ActionPerformed(evt);
            }
        });

        lblfee.setForeground(new java.awt.Color(0, 0, 240));
        lblfee.setText("Fee");

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblconfirm.setForeground(new java.awt.Color(153, 0, 0));

        jLabel11.setForeground(new java.awt.Color(0, 0, 240));
        jLabel11.setText("Term");

        jrterm1.setText("Term 1");
        jrterm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrterm1ActionPerformed(evt);
            }
        });

        jrterm2.setText("Term 2");
        jrterm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrterm2ActionPerformed(evt);
            }
        });

        jrterm3.setText("Term 3");
        jrterm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrterm3ActionPerformed(evt);
            }
        });

        btnok.setText("Ok");
        btnok.setEnabled(false);
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });

        jButton4.setText("Edit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel6)
                        .addGap(45, 45, 45)
                        .addComponent(lblconfirm)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(lblfee))
                                .addGap(179, 179, 179)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jrterm1)
                                        .addGap(198, 198, 198)
                                        .addComponent(jrterm3))
                                    .addComponent(txtfee))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnok)
                                .addGap(307, 307, 307)
                                .addComponent(jButton2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jrterm2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(91, 91, 91)
                                        .addComponent(cmbbordingdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(70, 70, 70)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(cmbclassname1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblconfirm))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbbordingdetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(cmbclassname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jrterm1)
                    .addComponent(jrterm2)
                    .addComponent(jrterm3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfee)
                    .addComponent(txtfee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(btnok))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbclassname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbclassname1ActionPerformed
        // TODO add your handling code here:
        selected = cmbclassname1.getSelectedIndex();
    }//GEN-LAST:event_cmbclassname1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String fee;
        fee = txtfee.getText();
         if("".equals(txtfee.getText()))
        {
            JOptionPane.showMessageDialog(null,
                "Please Enter Fee Ammount to Continue\n", "Warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            int clsidid = QueryClassDetails.listofnames.indexOf(classreq);
            clsid = Integer.parseInt(QueryClassDetails.listofids.get(clsidid).toString());
            
            termid = selects.QueryTermDetails.getTermID(termname, year);
            try {
                sqlupdates.MealsInfo.updateMealsFee(Double.parseDouble(fee), termid, clsid, fordetails);
                lblconfirm.setText("Updated");

            } catch (SQLException ex) {
                Logger.getLogger(NewTransport.class.getName()).log(Level.SEVERE, null, ex);
                if(ex.getErrorCode() == 1062)
                {
                    JOptionPane.showMessageDialog(null, "The Meals Fee Details You are Trying to Create Have Already Been Saved Before. \n" +
                        "Press Ok to continue", "Warning "+ex.getErrorCode(), JOptionPane.WARNING_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Some unexpected error occured \n" +
                        "Please contact the system administrator", "Error ", JOptionPane.ERROR_MESSAGE);
                    this.hide();
                }

            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jrterm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrterm1ActionPerformed
        // TODO add your handling code here:
        if(jrterm1.isSelected() == true)
        {
            jrterm2.setSelected(false);
            jrterm3.setSelected(false);
            termname = "FIRST TERM";
        }
    }//GEN-LAST:event_jrterm1ActionPerformed

    private void jrterm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrterm2ActionPerformed
        // TODO add your handling code here:
        if(jrterm2.isSelected() == true)
        {
            jrterm1.setSelected(false);
            jrterm3.setSelected(false);
            termname = "SECOND TERM";
        }
    }//GEN-LAST:event_jrterm2ActionPerformed

    private void jrterm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrterm3ActionPerformed
        // TODO add your handling code here:
        if(jrterm3.isSelected() == true)
        {
            jrterm2.setSelected(false);
            jrterm1.setSelected(false);
            termname = "THIRD TERM";
        }
    }//GEN-LAST:event_jrterm3ActionPerformed

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnokActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        fordetails = cmbbordingdetails.getSelectedItem().toString().toUpperCase();
        classreq = cmbclassname1.getSelectedItem().toString();
        if("SELECT".equals(fordetails))
        {
            JOptionPane.showMessageDialog(null,
                "Please Select Boarding Details to Continue\n", "Warning",JOptionPane.WARNING_MESSAGE);
        }
        else if(jrterm1.isSelected() == false && jrterm2.isSelected() == false && jrterm3.isSelected() == false)
        {
            JOptionPane.showMessageDialog(null,
                "Please Select Term to Continue\n", "Warning",JOptionPane.WARNING_MESSAGE);
        }
        //enter the other check details here
        else if(cmbclassname1.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(null,
                "Please Select a Class Name to Continue\n", "Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
         termid = selects.QueryTermDetails.getTermID(termname, year);
         clsid = QueryClassDetails.listofnames.indexOf(classreq);
         loadedfee = selects.QueryMealsDetails.getMealFee(termid, clsid, fordetails);
         if(!"".equals(loadedfee))
         {
         lblfee.setVisible(true);
         txtfee.setVisible(true);
         txtfee.setText(loadedfee);
         }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditMeals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditMeals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditMeals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditMeals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditMeals().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnok;
    private javax.swing.JComboBox cmbbordingdetails;
    private javax.swing.JComboBox cmbclassname1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrterm1;
    private javax.swing.JRadioButton jrterm2;
    private javax.swing.JRadioButton jrterm3;
    private javax.swing.JLabel lblconfirm;
    private javax.swing.JLabel lblfee;
    private javax.swing.JFormattedTextField txtfee;
    // End of variables declaration//GEN-END:variables
}
