/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package superadmin;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import selects.QueryClassDetails;

/**
 *
 * @author franq
 */
public class EditItemFee extends javax.swing.JFrame {

    /**
     * Creates new form SetItemFee
     */
    private static int borderinfo;
    private static String tablename;
    private int selected;
    private int totalnumclasses;
    private static int termid;
    private static String termname,year;
    private static boolean saved;
    
    
    public EditItemFee(int info, String itemname) {
        saved = false;
        initComponents();
        borderinfo = info;
        
        tablename = itemname;
        selected = 1;
        year = selects.QueryMainDetails.getCurrentYear();
        
        
        //get names of all members of staff
         QueryClassDetails.getClassNames();
         cmbclassname1.setModel(new DefaultComboBoxModel(QueryClassDetails.listofnames.toArray(new String[QueryClassDetails.listofnames.size()])));
         totalnumclasses = QueryClassDetails.listofnames.size();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cmbclassname1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtffee = new javax.swing.JFormattedTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblconfirm = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jrterm1 = new javax.swing.JRadioButton();
        jrterm3 = new javax.swing.JRadioButton();
        jrterm2 = new javax.swing.JRadioButton();
        btnok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Set Required Fee");
        setIconImage(selects.QueryMainDetails.setIcon());
        setResizable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 240));
        jLabel6.setText("Edit Fee Details");

        cmbclassname1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbclassname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbclassname1ActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(0, 0, 240));
        jLabel9.setText("Class");

        jLabel10.setForeground(new java.awt.Color(0, 0, 240));
        jLabel10.setText("Fee");

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Previous");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Next");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblconfirm.setForeground(new java.awt.Color(204, 0, 51));

        jLabel11.setForeground(new java.awt.Color(0, 0, 240));
        jLabel11.setText("Term");

        jrterm1.setText("Term 1");
        jrterm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrterm1ActionPerformed(evt);
            }
        });

        jrterm3.setText("Term 3");
        jrterm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrterm3ActionPerformed(evt);
            }
        });

        jrterm2.setText("Term 2");
        jrterm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrterm2ActionPerformed(evt);
            }
        });

        btnok.setText("Ok");
        btnok.setEnabled(false);
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel10))
                                        .addGap(374, 374, 374))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(lblconfirm))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(427, 427, 427)
                        .addComponent(jrterm1)
                        .addGap(81, 81, 81)
                        .addComponent(jrterm2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(jrterm3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(300, 300, 300)
                                .addComponent(jButton4)
                                .addGap(166, 166, 166)
                                .addComponent(jButton5))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(427, 427, 427)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnok)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cmbclassname1, 0, 388, Short.MAX_VALUE)
                                        .addComponent(jtffee)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(76, 76, 76))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblconfirm))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jrterm1)
                    .addComponent(jrterm3)
                    .addComponent(jrterm2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbclassname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtffee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(btnok))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbclassname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbclassname1ActionPerformed
        // TODO add your handling code here:
        selected = cmbclassname1.getSelectedIndex();
    }//GEN-LAST:event_cmbclassname1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(saved == true)
        {
        if(selected>=1)
        {
            selected--;
            cmbclassname1.setSelectedIndex(selected);
        }
        else
        {
            selected = totalnumclasses;
            cmbclassname1.setSelectedIndex(selected);
        }

        lblconfirm.setText("");
        btnok.setEnabled(false);
        saved = false;
        }
        else
            JOptionPane.showMessageDialog(null,
                "Please Save Information to Continue\n", "Warning",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(saved == true)
        {
        if(selected<=totalnumclasses)
        {
            selected++;
            cmbclassname1.setSelectedIndex(selected);
        }
        else
        {
            selected = 1;
            cmbclassname1.setSelectedIndex(selected);
        }
        lblconfirm.setText("");
        btnok.setEnabled(false);
        saved = false;
        }
        else
            JOptionPane.showMessageDialog(null,
                "Please Save Information To Continue\n", "Warning",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String pickpointname,classreq,fee;
        int classid;
        double feeammount;
        termid = selects.QueryTermDetails.getTermID(termname, year);
       
        classreq = cmbclassname1.getSelectedItem().toString();
        fee = jtffee.getText();
        if(jrterm1.isSelected() == false && jrterm2.isSelected() == false && jrterm3.isSelected() == false)
        {
            JOptionPane.showMessageDialog(null,
                "Please Select Term to Continue\n", "Warning",JOptionPane.WARNING_MESSAGE);
        }
        else if(cmbclassname1.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(null,
                "Please Select a Class Name to Continue\n", "Warning",JOptionPane.WARNING_MESSAGE);
        }
        else if("".equals(jtffee.getText()))
        {
            JOptionPane.showMessageDialog(null,
                "Please Fee Ammount to Continue\n", "Warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            int classidid = QueryClassDetails.listofnames.indexOf(classreq);
            classid = Integer.parseInt(QueryClassDetails.listofids.get(classidid).toString());
            feeammount = Double.parseDouble(fee);
            try {
                sqlinserts.NewFeeItemStuff.insertData(tablename,classid,termid,feeammount);
                lblconfirm.setText("Fee Details Saved");
                saved = true;
                btnok.setEnabled(true);
                

            } catch (SQLException ex) {
                Logger.getLogger(NewTransport.class.getName()).log(Level.SEVERE, null, ex);
                if(ex.getErrorCode() == 1062)
                {
                    try {
                        //sqlinserts.NewFeeItemStuff.insertData(tablename,classid,termid,feeammount);
                        sqlupdates.EditFeeItemStuff.insertData(tablename, classid, termid, feeammount);
                        lblconfirm.setText("Fee Details Updated");
                   
                        saved = true;
                        btnok.setEnabled(true);
                    } catch (SQLException ex1) {
                        Logger.getLogger(EditItemFee.class.getName()).log(Level.SEVERE, null, ex1);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Some unexpected error occured \n" +
                        "Please contact the system administrator", "Error ", JOptionPane.ERROR_MESSAGE);
                    this.hide();
                }

            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jrterm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrterm1ActionPerformed
        // TODO add your handling code here:
        if(jrterm1.isSelected() == true)
        {
            jrterm2.setSelected(false);
            jrterm3.setSelected(false);
            termname = "FIRST TERM";
        }
    }//GEN-LAST:event_jrterm1ActionPerformed

    private void jrterm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrterm2ActionPerformed
        // TODO add your handling code here:
        if(jrterm2.isSelected() == true)
        {
            jrterm1.setSelected(false);
            jrterm3.setSelected(false);
            termname = "SECOND TERM";
        }
    }//GEN-LAST:event_jrterm2ActionPerformed

    private void jrterm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrterm3ActionPerformed
        // TODO add your handling code here:
        if(jrterm3.isSelected() == true)
        {
            jrterm2.setSelected(false);
            jrterm1.setSelected(false);
            termname = "THIRD TERM";
        }
    }//GEN-LAST:event_jrterm3ActionPerformed

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditItemFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditItemFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditItemFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditItemFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditItemFee(borderinfo,tablename).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnok;
    private javax.swing.JComboBox cmbclassname1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrterm1;
    private javax.swing.JRadioButton jrterm2;
    private javax.swing.JRadioButton jrterm3;
    private javax.swing.JFormattedTextField jtffee;
    public javax.swing.JLabel lblconfirm;
    // End of variables declaration//GEN-END:variables
}
