/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package superadmin;

import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sqlinserts.InsertStaffPic;

/**
 *
 * @author franq
 */
public class NewStaff extends javax.swing.JFrame {

    /**
     * Creates new form NewStaff
     */
    
    private java.util.Date today;
    private static int currentuserid;
    
    public NewStaff(int userid) {
        initComponents();
        currentuserid = userid;
        today = new java.util.Date();
        this.setTitle("Staff Details");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        staffdetailspanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbstaffgender = new javax.swing.JComboBox();
        cmbstafftitle = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jtfsurname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtffirstname = new javax.swing.JTextField();
        jtflastname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtfjobtitle = new javax.swing.JTextField();
        jbtcancel = new javax.swing.JButton();
        jbtsave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtarole = new javax.swing.JTextArea();
        jtfnationalid = new javax.swing.JFormattedTextField();
        jXDOB = new com.toedter.calendar.JDateChooser();
        btncontinue = new javax.swing.JButton();
        btnok = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblsaved = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Staff Member");
        setIconImage(selects.QueryMainDetails.setIcon());
        setResizable(false);

        staffdetailspanel.setForeground(new java.awt.Color(0, 0, 240));

        jLabel1.setForeground(new java.awt.Color(0, 0, 240));
        jLabel1.setText("National ID");

        jLabel2.setForeground(new java.awt.Color(0, 0, 240));
        jLabel2.setText("Gender");

        jLabel10.setForeground(new java.awt.Color(0, 0, 240));
        jLabel10.setText("Title");

        cmbstaffgender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Male", "Female" }));

        cmbstafftitle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Mr", "Mrs", "Miss", "Dr", "Prof" }));
        cmbstafftitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbstafftitleActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(0, 0, 240));
        jLabel11.setText("Surname");

        jLabel12.setForeground(new java.awt.Color(0, 0, 240));
        jLabel12.setText("First Name");

        jLabel13.setForeground(new java.awt.Color(0, 0, 240));
        jLabel13.setText("Last Name");

        jLabel14.setForeground(new java.awt.Color(0, 0, 240));
        jLabel14.setText("Date of Birth");

        jLabel15.setForeground(new java.awt.Color(0, 0, 240));
        jLabel15.setText("Job Title");

        jLabel16.setForeground(new java.awt.Color(0, 0, 240));
        jLabel16.setText("Role");

        jbtcancel.setText("Cancel");
        jbtcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtcancelActionPerformed(evt);
            }
        });

        jbtsave.setText("Save");
        jbtsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtsaveActionPerformed(evt);
            }
        });

        jtarole.setColumns(20);
        jtarole.setRows(5);
        jScrollPane2.setViewportView(jtarole);

        try {
            jtfnationalid.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfnationalid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfnationalidActionPerformed(evt);
            }
        });

        btncontinue.setText("Continue");
        btncontinue.setEnabled(false);
        btncontinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncontinueActionPerformed(evt);
            }
        });

        btnok.setText("Ok");
        btnok.setEnabled(false);
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout staffdetailspanelLayout = new javax.swing.GroupLayout(staffdetailspanel);
        staffdetailspanel.setLayout(staffdetailspanelLayout);
        staffdetailspanelLayout.setHorizontalGroup(
            staffdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffdetailspanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(staffdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staffdetailspanelLayout.createSequentialGroup()
                        .addGroup(staffdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel14)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(staffdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jXDOB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbstaffgender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfnationalid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffdetailspanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(staffdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtcancel)
                            .addComponent(cmbstafftitle, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53)
                .addGroup(staffdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staffdetailspanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jbtsave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnok)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffdetailspanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfsurname, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffdetailspanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(jtffirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffdetailspanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtflastname, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffdetailspanelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfjobtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(staffdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffdetailspanelLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffdetailspanelLayout.createSequentialGroup()
                        .addComponent(btncontinue)
                        .addGap(82, 82, 82))))
        );
        staffdetailspanelLayout.setVerticalGroup(
            staffdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffdetailspanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(staffdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staffdetailspanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(staffdetailspanelLayout.createSequentialGroup()
                        .addGroup(staffdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbstaffgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jtfsurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(51, 51, 51)
                        .addGroup(staffdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jXDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(staffdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(jtffirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58)
                        .addGroup(staffdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfnationalid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel13)
                            .addComponent(jtflastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(staffdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfjobtitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(cmbstafftitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addGroup(staffdetailspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtcancel)
                            .addComponent(jbtsave)
                            .addComponent(btncontinue)
                            .addComponent(btnok))
                        .addGap(27, 27, 27))))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 240));
        jLabel6.setText("Enter The Staff Details");

        lblsaved.setForeground(new java.awt.Color(204, 0, 51));
        lblsaved.setText("Contacts Saved");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(staffdetailspanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel6)
                .addGap(43, 43, 43)
                .addComponent(lblsaved)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblsaved))
                .addGap(18, 18, 18)
                .addComponent(staffdetailspanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbstafftitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbstafftitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbstafftitleActionPerformed

    private void jbtcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtcancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtcancelActionPerformed

    private void jbtsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtsaveActionPerformed
        // TODO add your handling code here:
        String gender,title,nationalid,surname,fname,lname,dob,jobtitle,role,initpass;

        java.util.Date utildate = jXDOB.getDate();

        java.sql.Date sqldate = new java.sql.Date(utildate.getYear(),utildate.getMonth(),utildate.getDate());
        java.sql.Date todaysqldate = new java.sql.Date(today.getYear(), today.getMonth(), today.getDate());

        gender = cmbstaffgender.getSelectedItem().toString().toUpperCase();
        title = cmbstafftitle.getSelectedItem().toString().toUpperCase();
        nationalid = jtfnationalid.getText().toUpperCase();
        initpass = selects.QueryMainDetails.SHA256(nationalid);
        
        dob = sqldate.toString().toUpperCase();

        surname = jtfsurname.getText().toUpperCase();
        fname = jtffirstname.getText().toUpperCase();
        lname = jtflastname.getText().toUpperCase();
        jobtitle = jtfjobtitle.getText().toUpperCase();
        role = jtarole.getText().toUpperCase();

        if("SELECT".equals(gender)||gender == null||"".equals(gender))
        {
            JOptionPane.showMessageDialog(null,
                "Please Select Staffs' Gender to Continue\n", "Warning",JOptionPane.WARNING_MESSAGE);
        }
        else if("".equals(dob)||dob==null||sqldate==todaysqldate)
        {
            JOptionPane.showMessageDialog(null,
                "Please Enter  Staffs' Date of Birth to Continue\n", "Warning",JOptionPane.WARNING_MESSAGE);
        }

        else if(nationalid==null||"".equals(nationalid)||"        ".equals(nationalid))
        {
            JOptionPane.showMessageDialog(null,
                "Please Enter  Staffs' National ID number to Continue\n", "Warning",JOptionPane.WARNING_MESSAGE);
        }

        else if("SELECT".equals(title)||title == null ||"".equals(title))
        {
            JOptionPane.showMessageDialog(null,
                "Please Select Staffs' Title to Continue\n", "Warning",JOptionPane.WARNING_MESSAGE);
        }

        else if("".equals(surname)||surname == null)
        {
            JOptionPane.showMessageDialog(null,
                "Please Enter  Staffs' Surname to Continue\n", "Warning",JOptionPane.WARNING_MESSAGE);
        }
        else if("".equals(fname)||fname == null)
        {
            JOptionPane.showMessageDialog(null,
                "Please Enter  Staffs' First Name to Continue\n", "Warning",JOptionPane.WARNING_MESSAGE);
        }
        else if("".equals(lname)||lname == null)
        {
            JOptionPane.showMessageDialog(null,
                "Please Enter  Staffs' Last Name to Continue\n", "Warning",JOptionPane.WARNING_MESSAGE);
        }
        else if("".equals(jobtitle)||jobtitle == null)
        {
            JOptionPane.showMessageDialog(null,
                "Please Enter  Staffs' Job Title to Continue\n", "Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            try {
                // System.out.println(+" "+title+" "+nationalid+" "+dob+" "+surname+" "+fname+" "+lname+" "+jobtitle+" "+role);

                sqlinserts.NewStaff.registerStaff(nationalid, gender, title, surname, fname, lname, dob, jobtitle, role);
               
               // JOptionPane.showMessageDialog(null, "Staff Have Been Saved\n","Success", JOptionPane.INFORMATION_MESSAGE);
                //create login
                sqlinserts.NewLogin.createNewUser(nationalid, initpass, "nid", "2");
               
                this.lblsaved.setText("Details Saved");
                this.btncontinue.setEnabled(true);
                this.btnok.setEnabled(true);
                SuperAdmin.updateTable();
                int option = JOptionPane.showConfirmDialog(null, "Staff Details Successfylly Saved\n Do You Have Staffs' Passport Photo?","Success", JOptionPane.YES_NO_OPTION);
                if(option == JOptionPane.YES_OPTION)
                run();
                else{
                
                DBConnection dbconn = new DBConnection();
                Connection conn = dbconn.vconnection;
                PreparedStatement stmt = null;
                 String insert = "INSERT INTO `staff_passport`(`staffID`, `passport`)"
                + "VALUES(?,?)";
                stmt = conn.prepareStatement(insert);
                stmt.setInt(1,getStaffID());
                stmt.setBinaryStream(2,readDefaultStaffImage());
               
                stmt.executeUpdate();
            }
            }
            catch (SQLException ex) {
                Logger.getLogger(SuperAdmin.class.getName()).log(Level.SEVERE, null, ex);
                if(ex.getErrorCode() == 1062)
                {
                    JOptionPane.showMessageDialog(null, "The Staff Information   Has Already Been Saved Before. \n" +
                        "Press Ok to continue", "Warning "+ex.getErrorCode(), JOptionPane.WARNING_MESSAGE);
                }
                else
                JOptionPane.showMessageDialog(null, "Some unexpected error occured \n" +
                    "Please contact the system administrator", "Error "+ex.getErrorCode(), JOptionPane.WARNING_MESSAGE);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(NewStaff.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbtsaveActionPerformed

    //function to insert staff pic
     private void run() throws SQLException, FileNotFoundException {
                     InsertStaffPic ins;
                     ins = new InsertStaffPic(-1);
                          
            }
    
    private void jtfnationalidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfnationalidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfnationalidActionPerformed

    private void btncontinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncontinueActionPerformed
        // TODO add your handling code here:
        if(selects.QueryStafftDetails.getLastContact() != selects.QueryStafftDetails.getCurrentContactID())
        {
            JOptionPane.showMessageDialog(null,
                "Please Save Details to Continue\n", "Warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            NewStaffContact newcontacts = new NewStaffContact(currentuserid);
            newcontacts.main(new String[9]);
            this.dispose();
        }
    }//GEN-LAST:event_btncontinueActionPerformed

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
        // TODO add your handling code here:
        if(selects.QueryStafftDetails.getLastContact() != selects.QueryStafftDetails.getCurrentContactID())
        {
            JOptionPane.showMessageDialog(null,
                "Please Save Details First\n", "Warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
           this.dispose();
        }
    }//GEN-LAST:event_btnokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewStaff(currentuserid).setVisible(true);
            }
        });
        
    }
    
     //get the default staff image
    private InputStream readDefaultStaffImage()
    {
        DBConnection dbconn =new DBConnection();
        Connection conn = dbconn.vconnection;
        PreparedStatement pstmt;
        String sql = "SELECT `passport` FROM `staff_passport` WHERE `staffID`=-1";
        InputStream in = null;
        
        try {
            pstmt = conn.prepareStatement(sql);
            //should get the id of the current user and give it to 1
            //pstmt.setInt(1, currentUserId);
            ResultSet rs = pstmt.executeQuery();
            
            rs.next();
            in = rs.getBinaryStream("passport"); 
             
        } catch (SQLException ex) {
            Logger.getLogger(SuperAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        return in;
    }
   
    
    
    private static int getStaffID() throws SQLException
    {
        PreparedStatement stmt = null;
        int contid = 0;
        DBConnection dbconn = new DBConnection();
        Connection conn = dbconn.vconnection;
        
        
        String select = "SELECT  `ID` FROM  `staff` ORDER BY ID DESC LIMIT 1";
        try {
            stmt = conn.prepareStatement(select);
            
            ResultSet rs = stmt.executeQuery();
            
            while (rs.next()) {
 
				String userid = rs.getString("ID");
                                contid = Integer.parseInt(userid);
 
			}
            
            
        } catch (SQLException ex) {
            Logger.getLogger(sqlinserts.NewStaff.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Unexpected Error Occured \n" +
                        "Please Contact the System Administrator", "Error "+ex.getErrorCode(), JOptionPane.INFORMATION_MESSAGE);
        }
        finally {
 
			if (stmt != null) {
				stmt.close();
			}
 
			if (conn != null) {
				conn.close();
			}
 
		}
        return contid;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncontinue;
    private javax.swing.JButton btnok;
    private javax.swing.JComboBox cmbstaffgender;
    private javax.swing.JComboBox cmbstafftitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jXDOB;
    private javax.swing.JButton jbtcancel;
    private javax.swing.JButton jbtsave;
    private javax.swing.JTextArea jtarole;
    private javax.swing.JTextField jtffirstname;
    private javax.swing.JTextField jtfjobtitle;
    private javax.swing.JTextField jtflastname;
    private javax.swing.JFormattedTextField jtfnationalid;
    private javax.swing.JTextField jtfsurname;
    public javax.swing.JLabel lblsaved;
    private javax.swing.JPanel staffdetailspanel;
    // End of variables declaration//GEN-END:variables
}
