/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package departmenthead;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import selects.QueryClassDetails;
import selects.QueryStafftDetails;
import selects.QuerySubject;

/**
 *
 * @author franq
 */
public class NewSubjectTeacher extends javax.swing.JFrame {

    /**
     * Creates new form NewSubjectTeacher
     */
    
    private static int departmentid;
    
    public NewSubjectTeacher(int deptid) {
        departmentid = deptid;
        initComponents();
        //get names of subjects in that department
        QuerySubject.getSubject(departmentid);
        cmbsubject.setModel(new DefaultComboBoxModel(QuerySubject.listofnames.toArray(new String[QuerySubject.listofnames.size()])));
        
        //get names of all members of staff
         QueryStafftDetails.getStaffNames();
         cmbstaffname.setModel(new DefaultComboBoxModel(QueryStafftDetails.listofnames.toArray(new String[QueryStafftDetails.listofnames.size()])));
         //get names of all current classes
         QueryClassDetails.getClassNames();
         cmbclassname1.setModel(new DefaultComboBoxModel(QueryClassDetails.listofnames.toArray(new String[QueryClassDetails.listofnames.size()])));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbsubject = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jbuttoncancelcontacts1 = new javax.swing.JButton();
        jbuttoncancelcontacts2 = new javax.swing.JButton();
        cmbstaffname = new javax.swing.JComboBox();
        cmbclassname1 = new javax.swing.JComboBox();
        btnok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Subject Teacher");
        setIconImage(selects.QueryMainDetails.setIcon());
        setResizable(false);

        jLabel5.setForeground(new java.awt.Color(0, 0, 240));
        jLabel5.setText("Subject");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 240));
        jLabel8.setText("Enter Details");

        jLabel6.setForeground(new java.awt.Color(0, 0, 240));
        jLabel6.setText("Class");

        cmbsubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbsubjectActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 0, 240));
        jLabel7.setText("Teacher");

        jbuttoncancelcontacts1.setText("Cancel");
        jbuttoncancelcontacts1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttoncancelcontacts1ActionPerformed(evt);
            }
        });

        jbuttoncancelcontacts2.setText("Save");
        jbuttoncancelcontacts2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttoncancelcontacts2ActionPerformed(evt);
            }
        });

        btnok.setText("Ok");
        btnok.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 314, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbsubject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbstaffname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbclassname1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(158, 158, 158))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbuttoncancelcontacts1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnok)
                        .addGap(188, 188, 188)
                        .addComponent(jbuttoncancelcontacts2)
                        .addGap(146, 146, 146))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cmbsubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbclassname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbstaffname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuttoncancelcontacts1)
                    .addComponent(jbuttoncancelcontacts2)
                    .addComponent(btnok))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbsubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbsubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbsubjectActionPerformed

    private void jbuttoncancelcontacts1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttoncancelcontacts1ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jbuttoncancelcontacts1ActionPerformed

    private void jbuttoncancelcontacts2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttoncancelcontacts2ActionPerformed
       String classname,teachername,tn,cls,subjectname,subj;
        int classid,staffid,subjectid;
        
        subj = cmbsubject.getSelectedItem().toString();
        subjectname = subj.toUpperCase();
        cls = cmbclassname1.getSelectedItem().toString();
        classname = cls.toUpperCase();
        tn = cmbstaffname.getSelectedItem().toString();
        teachername = tn.toUpperCase();
        
        if("SELECT SUBJECT".equals(subjectname))
        {
            JOptionPane.showMessageDialog(null,
                        "Please Select Subject to Continue\n", "Warning",JOptionPane.WARNING_MESSAGE);
        }
        else if("SELECT CLASS NAME".equals(classname))
        {
            JOptionPane.showMessageDialog(null,
                        "Please Select Class Name to Continue\n", "Warning",JOptionPane.WARNING_MESSAGE);
        }
        else if("SELECT MEMBER OF STAFF".equals(teachername))
        {
            JOptionPane.showMessageDialog(null,
                        "Please Select Class Teacher to Continue\n", "Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
             staffid = QueryStafftDetails.listofnames.indexOf(tn);
             classid = QueryClassDetails.listofnames.indexOf(cls);
             subjectid = QuerySubject.listofnames.indexOf(tn);
           try {
               //insert in to database
               sqlinserts.NewSubject.setsubjectTeacher(subjectid, staffid, classid);
               JOptionPane.showMessageDialog(null, "Subject Teacher Registered \n" +
                        "Press Ok to Continue", "Success ", JOptionPane.INFORMATION_MESSAGE);
               btnok.setEnabled(true);
               
           } catch (SQLException ex) {
               Logger.getLogger(NewSubjectTeacher.class.getName()).log(Level.SEVERE, null, ex);
               
               
            if(ex.getErrorCode()==1062)
            {
            JOptionPane.showMessageDialog(null, "Subject Teacher Details have already been set. \n" +
                        "Click update to change", "Error "+ex.getErrorCode(), JOptionPane.INFORMATION_MESSAGE);
            }
            else 
                {
                    JOptionPane.showMessageDialog(null, "Unknown Error. \n" +
                    "Press Contact the Administrator for further advice", "Error "+ex.getErrorCode(), JOptionPane.INFORMATION_MESSAGE);
                }
           }
             
        }
    }//GEN-LAST:event_jbuttoncancelcontacts2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewSubjectTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewSubjectTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewSubjectTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewSubjectTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewSubjectTeacher(departmentid).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnok;
    private javax.swing.JComboBox cmbclassname1;
    private javax.swing.JComboBox cmbstaffname;
    private javax.swing.JComboBox cmbsubject;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbuttoncancelcontacts1;
    private javax.swing.JButton jbuttoncancelcontacts2;
    // End of variables declaration//GEN-END:variables
}
